/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shivam
 */
public class index extends javax.swing.JFrame {
  private static  String action ="";
  static double sum;
  static double num1=0;
  static double num2 =0;
  static String operation ="";
   
   /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtval = new javax.swing.JTextField();
        jbtn_2 = new javax.swing.JButton();
        jbtn_1 = new javax.swing.JButton();
        jbtn_3 = new javax.swing.JButton();
        jbtn_plus = new javax.swing.JButton();
        jbtn_4 = new javax.swing.JButton();
        jbtn_6 = new javax.swing.JButton();
        jbtn_5 = new javax.swing.JButton();
        jbtn_8 = new javax.swing.JButton();
        jbtn_9 = new javax.swing.JButton();
        jbtn_multi = new javax.swing.JButton();
        jbtn_7 = new javax.swing.JButton();
        jbtn_minus = new javax.swing.JButton();
        jbtn_divide = new javax.swing.JButton();
        jbtn_enter = new javax.swing.JButton();
        jbtn_0 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtn_decimal = new javax.swing.JButton();
        jbtn_clear = new javax.swing.JButton();
        jbtn_back = new javax.swing.JButton();
        jbtn_power = new javax.swing.JButton();
        jbtn_sqt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn_2.setText("2");
        jbtn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_2ActionPerformed(evt);
            }
        });

        jbtn_1.setText("1");
        jbtn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_1ActionPerformed(evt);
            }
        });

        jbtn_3.setText("3");
        jbtn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_3ActionPerformed(evt);
            }
        });

        jbtn_plus.setText("+");
        jbtn_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_plusActionPerformed(evt);
            }
        });

        jbtn_4.setText("4");
        jbtn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_4ActionPerformed(evt);
            }
        });

        jbtn_6.setText("6");
        jbtn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_6ActionPerformed(evt);
            }
        });

        jbtn_5.setText("5");
        jbtn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_5ActionPerformed(evt);
            }
        });

        jbtn_8.setText("8");
        jbtn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_8ActionPerformed(evt);
            }
        });

        jbtn_9.setText("9");
        jbtn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_9ActionPerformed(evt);
            }
        });

        jbtn_multi.setText("*");
        jbtn_multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_multiActionPerformed(evt);
            }
        });

        jbtn_7.setText("7");
        jbtn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_7ActionPerformed(evt);
            }
        });

        jbtn_minus.setText("-");
        jbtn_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_minusActionPerformed(evt);
            }
        });

        jbtn_divide.setText("/");
        jbtn_divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_divideActionPerformed(evt);
            }
        });

        jbtn_enter.setText("Enter");
        jbtn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_enterActionPerformed(evt);
            }
        });

        jbtn_0.setText("0");
        jbtn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_0ActionPerformed(evt);
            }
        });

        jLabel1.setText("<html>\n<b>\nDeveloped By Shivam Sharma Google.inc\n</b>\n</html>");

        jbtn_decimal.setText(".");
        jbtn_decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_decimalActionPerformed(evt);
            }
        });

        jbtn_clear.setText("Clear");
        jbtn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_clearActionPerformed(evt);
            }
        });

        jbtn_back.setText("-");
        jbtn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_backActionPerformed(evt);
            }
        });

        jbtn_power.setText("<html> X<sup>2</sup> </html>");
        jbtn_power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_powerActionPerformed(evt);
            }
        });

        jbtn_sqt.setText("sqt");
        jbtn_sqt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_sqtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtval, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_4)
                            .addComponent(jbtn_7)
                            .addComponent(jbtn_1)
                            .addComponent(jbtn_0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_8)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jbtn_2)
                                    .addGap(9, 9, 9))
                                .addComponent(jbtn_5))
                            .addComponent(jbtn_decimal))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_9)
                            .addComponent(jbtn_6)
                            .addComponent(jbtn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_sqt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jbtn_power, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_divide, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtn_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtn_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(txtval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_2)
                    .addComponent(jbtn_3)
                    .addComponent(jbtn_plus)
                    .addComponent(jbtn_1)
                    .addComponent(jbtn_minus))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_5)
                    .addComponent(jbtn_4)
                    .addComponent(jbtn_6)
                    .addComponent(jbtn_multi)
                    .addComponent(jbtn_divide))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_8)
                    .addComponent(jbtn_9)
                    .addComponent(jbtn_7)
                    .addComponent(jbtn_clear))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_0)
                    .addComponent(jbtn_decimal)
                    .addComponent(jbtn_back)
                    .addComponent(jbtn_enter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_sqt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_power, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_2ActionPerformed
        // TODO add your handling code here:
       String text = txtval.getText() + jbtn_2.getText();
            txtval.setText(text);
    }//GEN-LAST:event_jbtn_2ActionPerformed

    private void jbtn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_1ActionPerformed
            String text = txtval.getText() + jbtn_1.getText();
            txtval.setText(text);
           
             
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_1ActionPerformed

    private void jbtn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_3ActionPerformed
        String text = txtval.getText() + jbtn_3.getText();
            txtval.setText(text);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_3ActionPerformed

    private void jbtn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_4ActionPerformed
        // TODO add your handling code here:
        String text = txtval.getText() + jbtn_4.getText();
            txtval.setText(text);
    }//GEN-LAST:event_jbtn_4ActionPerformed

    private void jbtn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_5ActionPerformed
        // TODO add your handling code here:
        String text = txtval.getText() + jbtn_5.getText();
            txtval.setText(text);
    }//GEN-LAST:event_jbtn_5ActionPerformed

    private void jbtn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_6ActionPerformed
          String text = txtval.getText() + jbtn_6.getText();
            txtval.setText(text);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_6ActionPerformed

    private void jbtn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_7ActionPerformed
        // TODO add your handling code here:
        String text = txtval.getText() + jbtn_7.getText();
            txtval.setText(text);
    }//GEN-LAST:event_jbtn_7ActionPerformed

    private void jbtn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_8ActionPerformed
        // TODO add your handling code here:
        String text = txtval.getText() + jbtn_8.getText();
            txtval.setText(text);
    }//GEN-LAST:event_jbtn_8ActionPerformed

    private void jbtn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_9ActionPerformed
        // TODO add your handling code here:
       String text = txtval.getText() + jbtn_9.getText();
            txtval.setText(text);
    }//GEN-LAST:event_jbtn_9ActionPerformed

    private void jbtn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_0ActionPerformed
      String text = txtval.getText()  + jbtn_0.getText();
            txtval.setText(text);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_0ActionPerformed

    private void jbtn_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_plusActionPerformed
        // TODO add your handling code here:
          action="+";
        num1 = Double.valueOf(txtval.getText());
        txtval.setText("");
    }//GEN-LAST:event_jbtn_plusActionPerformed

    private void jbtn_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_minusActionPerformed
        // TODO add your handling code here:
             action ="-";
             num1 = Double.valueOf(txtval.getText());
             txtval.setText("");
    }//GEN-LAST:event_jbtn_minusActionPerformed

    private void jbtn_multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_multiActionPerformed
            action ="*";
            num1 = Double.valueOf(txtval.getText());
            txtval.setText("");
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_multiActionPerformed

    private void jbtn_divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_divideActionPerformed
            action ="/";
            num1 = Double.valueOf(txtval.getText());
            txtval.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_divideActionPerformed

    private void jbtn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_enterActionPerformed
       num2 = Double.valueOf(txtval.getText());
        if("+".equals(action)){            
              sum =num1+num2;
            txtval.setText(String.valueOf(sum));
        }else if("-".equals(action)){
                sum =num1-num2;
            txtval.setText(String.valueOf(sum));
        }else if("*".equals(action)){
        sum =num1*num2;
            txtval.setText(String.valueOf(sum));
        }else if("/".equals(action)){
          sum =num1/num2;
            txtval.setText(String.valueOf(sum));
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_enterActionPerformed

    private void jbtn_decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_decimalActionPerformed
        // TODO add your handling code here:
        String text = txtval.getText() + jbtn_decimal.getText();
        txtval.setText(text);
    }//GEN-LAST:event_jbtn_decimalActionPerformed

    private void jbtn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_clearActionPerformed
            txtval.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_clearActionPerformed

    private void jbtn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_backActionPerformed
        // TODO add your handling code here:
        String text = txtval.getText();
        text = text.substring(0,text.length()-1);
        txtval.setText(text);
    }//GEN-LAST:event_jbtn_backActionPerformed

    private void jbtn_powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_powerActionPerformed
        // TODO add your handling code here:
        num1 = Double.valueOf(txtval.getText());
        double power= Math.pow(num1, 2);
        txtval.setText(String.valueOf(power));
    }//GEN-LAST:event_jbtn_powerActionPerformed

    private void jbtn_sqtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_sqtActionPerformed
        // TODO add your handling code here:
        num1 = Double.valueOf(txtval.getText());
          double square = Math.sqrt(num1);
          txtval.setText(String.valueOf(square));
    }//GEN-LAST:event_jbtn_sqtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtn_0;
    private javax.swing.JButton jbtn_1;
    private javax.swing.JButton jbtn_2;
    private javax.swing.JButton jbtn_3;
    private javax.swing.JButton jbtn_4;
    private javax.swing.JButton jbtn_5;
    private javax.swing.JButton jbtn_6;
    private javax.swing.JButton jbtn_7;
    private javax.swing.JButton jbtn_8;
    private javax.swing.JButton jbtn_9;
    private javax.swing.JButton jbtn_back;
    private javax.swing.JButton jbtn_clear;
    private javax.swing.JButton jbtn_decimal;
    private javax.swing.JButton jbtn_divide;
    private javax.swing.JButton jbtn_enter;
    private javax.swing.JButton jbtn_minus;
    private javax.swing.JButton jbtn_multi;
    private javax.swing.JButton jbtn_plus;
    private javax.swing.JButton jbtn_power;
    private javax.swing.JButton jbtn_sqt;
    private javax.swing.JTextField txtval;
    // End of variables declaration//GEN-END:variables
}
